### ISSUE TITLE
Refactor Helm values file

### ISSUE THREAD

**Issue by sonnysideup** [dominodatalab/hephaestus#21]
The Helm chart contains values that affect both the `controller` and `logProcessor` and, since those are both top-level keys, there's currently no way to scope them such that they clearly apply to both w/o applying to the buildkit workload. The `values.yaml` probably needs to be refactored to indicate that both of these elements live together.

```yaml
buildkit:
  # buildkit things

controller:
  # controller-scoped global values shared by the following two

  manager: # manager-specific

  vector: # vector-specific
```
